#!/usr/bin/env bash
#
# Remove case data downloaded by ig.get_case_data() and files generated by the
# examples, from examples/ and from every gallery section.
#
# Each gallery example runs with its own directory as the working directory
# (sphinx-gallery does this), so downloaded data accumulates once per section
# rather than in one shared place.
#
# Only generated files are removed. The example .py files and each section's
# GALLERY_HEADER.rst are left alone.

set -u
shopt -s nullglob

# Anchor to this script's directory, so running it from elsewhere cannot delete
# data files in whatever happens to be the current directory.
cd "$(dirname "$0")" || exit 1

total=0
for dir in . gallery/*/; do
    [ -d "$dir" ] || continue
    files=("$dir"*.h5 "$dir"*.stm "$dir"*.gex "$dir"*.txt "$dir"*.csv \
           "$dir"*.xyz "$dir"README_*)
    #files+=("$dir"*.png "$dir"*.npz)   # uncomment to drop figures/timings too
    if [ ${#files[@]} -gt 0 ]; then
        printf '%-34s %d file(s)\n' "${dir%/}" "${#files[@]}"
        rm -f "${files[@]}"
        total=$((total + ${#files[@]}))
    fi
done

echo "removed $total file(s)"
